name: solidart_devtools_extension
description: "solidart DevTools extension"
publish_to: "none"
version: 0.2.1

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  devtools_extensions: ^0.3.1
  devtools_app_shared: ^0.3.1
  flutter_solidart:
    path: ../flutter_solidart
  collection: ^1.18.0
  shadcn_ui: ^0.22.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
