name: solidart_devtools_extension
description: "solidart DevTools extension"
publish_to: "none"
version: 0.2.1

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  devtools_extensions: 0.3.0
  devtools_app_shared: 0.3.0
  flutter_solidart:
    path: ../flutter_solidart
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

dependency_overrides:
  vm_service: ^13.0.0

flutter:
  uses-material-design: true
