name: solidart_devtools_extension
description: "solidart DevTools extension"
publish_to: "none"
version: 0.2.0

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  devtools_extensions: 0.0.9
  devtools_app_shared: 0.0.5
  flutter_solidart:
    path: ../flutter_solidart
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
