codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "70...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

# excluding examples from the coverage report
ignore:
  - "**/example/"
  - "examples"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
