name: Melos

packages:
  - packages/*

scripts:
  analyze:
    run: melos exec -- dart analyze .
    description: Run `dart analyze` in all packages.

  test:
    run: very_good test --recursive --coverage --min-coverage 85
    description: Run Dart and Flutter tests
    select-package:
      dir-exists: test

  combine_coverage: melos exec -- "\$MELOS_ROOT_PATH/scripts/combine_coverage.sh"
