name: Melos

packages:
  - packages/solidart
  - packages/flutter_solidart

scripts:
  analyze:
    run: melos exec -- dart analyze .
    description: Run `dart analyze` in all packages.

  test:
    run: |
      yes 2>/dev/null | very_good --analytics false && \
      melos exec -- very_good test --recursive --coverage --min-coverage 85
    description: Run Dart and Flutter tests
    select-package:
      flutter: true
      dir-exists: test

  combine_coverage: melos exec -- "\$MELOS_ROOT_PATH/scripts/combine_coverage.sh"
