include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    always_put_required_named_parameters_first: ignore
  plugins:
    - custom_lint

linter:
  rules:
    # since this is just an example, there is no need for ubiquitous documentation.
    public_member_api_docs: false
