name: solidart_hooks
description: Flutter Hooks bindings for Solidart, suitable for ephemeral state and for writing less boilerplate.
version: 1.0.0+1
repository: https://github.com/nank1ro/solidart
documentation: https://solidart.mariuti.com
topics:
  - state-management
  - signals
  - hooks

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  solidart: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0
