include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    inference_failure_on_instance_creation: error

linter:
  rules:
    always_put_required_named_parameters_first: false
    use_late_for_private_fields_and_variables: false
    implicit_call_tearoffs: false
