name: Publish flutter_solidart to pub.dev

on:
  push:
    tags:
      - 'flutter_solidart-v[0-9]+.[0-9]+.[0-9]+'          # Matches flutter_solidart-v1.2.3
      - 'flutter_solidart-v[0-9]+.[0-9]+.[0-9]+\+[0-9]+'  # Matches flutter_solidart-v1.2.3+1

# Publish using the reusable workflow from dart-lang.
jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      environment: pub.dev
