name: Publish solidart to pub.dev

on:
  push:
    tags:
      - 'solidart-v[0-9]+.[0-9]+.[0-9]+'          # Matches solidart-v1.2.3
      - 'solidart-v[0-9]+.[0-9]+.[0-9]+\+[0-9]+'  # Matches solidart-v1.2.3+1

# Publish using the reusable workflow from dart-lang.
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for authentication using OIDC
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: |
          flutter pub get
          cd packages/solidart_devtools_extension
          dart run devtools_extensions build_and_copy --source=. --dest=../solidart/extension/devtools
      - name: Publish - dry run
        run: dart pub publish --dry-run
        working-directory: packages/solidart
      # Publishing...
      - name: Publish to pub.dev
        run: dart pub publish -f
        working-directory: packages/solidart
