analyzer:
  errors:
    avoid_catches_without_on_clauses: ignore
    discarded_futures: ignore
    document_ignores: ignore
    prefer_foreach: ignore
include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    use_late_for_private_fields_and_variables: false
    implicit_call_tearoffs: false
